#!/usr/bin/env python
# coding: utf8
from fabric.api import local
from fabric.colors import green
local('rsync -av --delete site/ www@rtts.eu:artworksinmotion')
print green('Let’s watch some art!', bold=True)
